# Generated by Django 4.1.5 on 2023-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
