# Generated by Django 4.2.3 on 2023-07-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='image',
        ),
    ]
